# Generated by Django 5.0.3 on 2024-04-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeping_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Keeper',
        ),
    ]
