# Generated by Django 5.0.3 on 2024-04-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeping_app', '0003_apiary_company_apiary_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiary',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/company_logos/'),
        ),
    ]
