# Generated by Django 5.0.3 on 2024-04-20 20:10

import beekeeping_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeping_app', '0005_alter_apiary_company_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apiary',
            name='owner',
            field=models.CharField(max_length=200, default=''),
        ),
    ]