# Generated by Django 5.0.3 on 2024-04-21 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beekeeping_app', '0008_remove_apiary_owner_keeper_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keeper',
            name='apiary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keeper', to='beekeeping_app.apiary'),
        ),
    ]
